# attention: l'image docker ne contient que la CLI
# pour accéder à un démon docker, deux possibilités:

## 1. partager la socker unix de la VM dans la conf du runner
##    "volumes = ["/var/run/docker.sock:/var/run/docker.sock",...]"
##    dans /etc/gitlab-runner/config.toml
##    attention: solution insecure car accès de TOUS les contenurs du pipeline
##    au dockerd de la vm (faille possible)

# 2. adjoindre au job un sevice conteneur "docker in docker" contenant un démon
## service docker:20.10.23-dind
## doit être lancé avec privilege étendu dans la conf du runner
## les certificats client et serveur doivent être partagés avec la vm dans la conf
## DOCKER_TLS_CERTDIR
image: docker:20.10.23

variables:
  TOMCAT_VERSION_MAJOR: 8
  TOMCAT_VERSION_MINOR: 8.5.85
  # DOCKER_TLS_CERTDIR: /certs
  TRIGGER_BUILD: "off"

stages:
  - build image
  - test image

# before_script global, exécuté avant les scripts de chaque job
before_script:
  # préférer un deploy token (ne fonctionne pas en 15.7.5) 
  # ou un personal token + variable secrète plutôt que des ids gitlab 
  - >
    echo "$REGISTRY_TOKEN" |
    docker login $CI_REGISTRY
    -u "$CI_REGISTRY_USER"
    --password-stdin


docker build:
  stage: build image
  # services:
  #   - docker:20.10.23-dind
  script:
    - >
      docker build -t $CI_REGISTRY_IMAGE/my_tomcat_app:rc-1.0 
      --build-arg TOMCAT_VERSION_MAJOR=$TOMCAT_VERSION_MAJOR
      --build-arg TOMCAT_VERSION_MINOR=$TOMCAT_VERSION_MINOR .
    # vérification du HEALTHCHECK
    - docker run -d --name test_build my_tomcat_app:rc-1.0
    - sleep 5
    - docker ps -f name="test_build" | grep -o "(healthy)"
    # upload de l'image sur le registre d'image privé de gitlab
    - docker push $CI_REGISTRY_IMAGE/my_tomcat_app:rc-1.0
  # nettoyage du conteneur de test pour éviter de planter à la porchaine exécution
  after_script:
    - docker stop test_build && docker rm test_build
  tags:
    - myusine
  # on ne build que si le Dockerfile a changé
  # ou si on passe nous même une variable à "on"
  rules:
    - changes: [Dockerfile]
    - if: $TRIGGER_BUILD == "on"

scan:
  stage: test image
  # connexion de trivy au registre d'image
  variables:
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$REGISTRY_TOKEN"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
  image:
    name: aquasec/trivy
    # désactivation de l'entrypoint de l'image trivy de base
    entrypoint: [""]
  tags:
    - myusine
  # subsidiarité: neutralisation du before_script global par le before_script local
  # ... car le conteneur trivy ne contient pas les commandes docker !!!
  before_script: [""]
  script:
    # --severity: seuil de vulnérabilité pour l'analyse
    # --no-progress: nettoyer la console
    # --cache-dir: placer le cache là où gitlab peut le prélever
    - >
      trivy image 
      --severity HIGH
      --no-progress
      --cache-dir .trivycache/
      $CI_REGISTRY_IMAGE/my_tomcat_app:rc-1.0
  cache:
    key: trivy
    paths:
      - .trivycache/
    policy: pull-push