image: docker:26.1.3

stages:
  - build

build:
  stage: build
  tags:
    - myusine
  script:
    - cd app-java/tomcat
    - >
      docker build 
      -t app-java-tomcat:1.0
      --build-arg TOMCAT_VERSION_MAJOR=9
      --build-arg TOMCAT_VERSION_FULL=9.0.89
      --build-arg CI_API_V4_URL=$CI_API_V4_URL
      --build-arg CI_PROJECT_ID=$CI_PROJECT_ID
      --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN
      .