image: docker:20.10.23

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

variables:
  BASE_TAG: 7.9.2009
  TOMCAT_VERSION_MAJOR: 8
  TOMCAT_VERSION_MINOR: 8.5.85
  DOCKER_TLS_CERTDIR: /certs
  TRIGGER_BUILD: "off"

stages:
  - get app
  - build image
  - test image
  - confirm image
  - staging

before_script:
  - >
    echo "$REGISTRY_TOKEN" |
    docker login $CI_REGISTRY
    -u "$CI_REGISTRY_USER"
    --password-stdin


get app:
  stage: get app
  tags: [myusine]
  image: maven:3.8.7-eclipse-temurin-17-focal
  before_script:
    - echo "$GITLAB_ROOT_CA" > /usr/local/share/ca-certificates/gitlab.myusine.fr.pem
    - update-ca-certificates
    - >
      keytool 
      -import 
      -trustcacerts
      -storepass changeit 
      -noprompt
      -alias my-gitlab 
      -file /usr/local/share/ca-certificates/gitlab.myusine.fr.pem 
      -keystore "$JAVA_HOME/lib/security/cacerts"
  script:
    - >
      mvn dependency:copy-dependencies
      -DoutputDirectory=$CI_PROJECT_DIR
      -s ci_settings.xml
  artifacts:
    expire_in: "10 minutes"
    paths:
      - *.jar

.docker build:
  stage: build image
  script:
    - >
      docker build -t "$CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc" 
      --build-arg TOMCAT_VERSION_MAJOR=$TOMCAT_VERSION_MAJOR
      --build-arg TOMCAT_VERSION_MINOR=$TOMCAT_VERSION_MINOR 
      --build-arg BASE_TAG=$BASE_TAG .
    - docker run -d --name test_build $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
    - sleep 5
    - docker ps -f name="test_build" | grep -o "(healthy)"
    - docker push $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
  after_script:
    - docker stop test_build && docker rm test_build
    # - docker rmi $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
  tags: [myusine]
  rules:
    - changes: [Dockerfile]
      if: $CI_COMMIT_BRANCH
    - if: $TRIGGER_BUILD == "on" && $CI_COMMIT_BRANCH

.scan:
  stage: test image
  variables:
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$REGISTRY_TOKEN"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    TRIVY_INSECURE: "true"
    TRIVY_OPTS: >
                --severity HIGH
                --scanners vuln
                --no-progress
                --cache-dir .trivycache/
                --format template
  image:
    name: aquasec/trivy
    entrypoint: [""]
  tags: [myusine]
  # neutralise le before_script global
  before_script: [""]
  script:
    # - >
    #   trivy image 
    #   $TRIVY_OPTS
    #   --template "@/contrib/gitlab.tpl" 
    #   --output "$CI_PROJECT_DIR/gl-container-scanning-report.json"
    #   $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
    - >
      trivy image 
      $TRIVY_OPTS
      --template "@/contrib/html.tpl" 
      --output "$CI_PROJECT_DIR/html-container-scanning-report.html"
      $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
  cache:
    key: trivy
    paths:
      - .trivycache/
    policy: pull-push
  artifacts:
    expire_in: "1 hour"
    paths:
      - html-container-scanning-report.html
    # pour intégration dans gitlab pour version < 15 (pas gratuit)
    # reports:
    #   container_scanning: gl-container-scanning-report.json
  rules:
    - changes: [Dockerfile]
      if: $CI_COMMIT_BRANCH
    - if: $TRIGGER_BUILD == "on" && $CI_COMMIT_BRANCH

# TODO: supprimer un tag "rc" à distance via une requête HTTP avec curl
# et l'api du registre
# ou mettre en place le nttoyage de tag dans project -> settings -> packages & registries
.push image:
  tags: [myusine]
  stage: confirm image
  script:
    - docker pull $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
    - >
      docker tag 
      $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
      $CI_REGISTRY_IMAGE/my_tomcat_app:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE/my_tomcat_app:$CI_COMMIT_TAG
    - docker rmi $CI_REGISTRY_IMAGE/my_tomcat_app:$GITLAB_USER_NAME-rc
    # - docker rmi $CI_REGISTRY_IMAGE/my_tomcat_app:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

.deploy:
  image: alpinelinux/ansible:latest
  stage: staging
  tags: [myusine]
  before_script:
    - mkdir ~/.ssh
    - echo "$STAGING_PRIVKEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 400 ~/.ssh/id_rsa
    - mv ansible.cfg ~/.ansible.cfg
    - mv inventory ~/inventory
    - "ansible-galaxy collection install community.docker:==2.7.4"
  script:
    - >
      ansible-playbook 
      -e "ansible_become_pass=$STAGING_PSSWD"
      -e extra_registry_login=$CI_REGISTRY_USER 
      -e extra_registry_pwd=$REGISTRY_TOKEN
      -e extra_image_tag=$CI_COMMIT_TAG
      playbook_main.yml
  environment:
    name: staging
    url: http://gitlab.myusine.fr:8081
  rules:
    - if: $CI_COMMIT_TAG
  
