
- name: DOCKER | install prerequisites
  ansible.builtin.apt:
    name: "{{ item }}" 
      # - ca-certificates 
      # - curl
    state: present
    update_cache: true
  with_items: "{{ docker_prerequisites }}"
  when: ansible_os_family == "Debian"

## le module file est IDEMPOTENT i.e si le dossier existe, nul besoin d'exécuter
- name: DOCKER | add directory for host the key
  ansible.builtin.file:
    path: "{{ docker_key_dir }}"
    state: directory
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: DOCKER | download GPG key
  ansible.builtin.get_url:
    url: "{{ docker_key_url }}"
    dest: "{{ docker_key_dir }}/docker.asc"
    mode: '0644'
    force: true
  when: ansible_os_family == "Debian"

- name: DOCKER | add docker-ce version apt pref file
  ansible.builtin.template:
    src: docker-ce.pref.j2
    dest: /etc/apt/preferences.d/docker-ce.pref
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "Debian"
    


  