---
# tasks file for install-docker

- name: INSTALL | check docker install-docker
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: check_docker

- name: INSTALL | install docker
  import_tasks: "{{ role_path }}/tasks/docker.yml"
  tags: 
    - 'role:docker'
  when: not check_docker.stat.exists

- name: DOCKER | add docker-ce version apt pref file
  ansible.builtin.template:
    src: docker-ce.pref.j2
    dest: /etc/apt/preferences.d/docker-ce.pref
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "Debian"
    
