# pour les images de base (distribution linux)
# pour lancer des exécutables
# FROM scratch
FROM httpd:2.4

LABEL author="matt"
LABEL created_at="2024-06-12"
LABEL created_at.year="2024"
LABEL stack="java"
LABEL stack.item="httpd"


